### ISSUE TITLE
Add deconstruct method to Success class so one can get direct reference to payload

### ISSUE THREAD

**Issue by MiniRoman** [MNie/ResultType#2]
So as in a title, Deconstruct method on Success class would be useful to get the Payload of success type, so instead of polluting scope with unnecessary Success<> variable, we could get direct reference to payload value.

```
public class Success<TPayload> : IResult<TPayload>
{
        ...
        public void Deconstruct(out TPayload payload)
        {
            payload = Payload;
        }
}
```

Use example:
```
parentCount is Result.Success<int> (var count) && count > 0 
```

**Comment by MNie** [comment]
`Payload` is available in a `Success<T>` class. So you could use that as `successResult.Payload` there is no need for an additional function which would do simply the same.
